<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="CRUD_WITH_GRIDVIEW.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 47px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" ShowFooter="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <Columns>
                <asp:TemplateField HeaderText="Id" InsertVisible="False" SortExpression="Id">
                    <EditItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Eval("Id") %>'></asp:Label>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>

                        <asp:LinkButton OnClick="LinkButton1_Click" ValidationGroup="Insert" runat="server">Insert</asp:LinkButton>

                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="name" SortExpression="name">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
               
                        <asp:RequiredFieldValidator ControlToValidate="TextBox1" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Name Is A Required Field"></asp:RequiredFieldValidator>   
                 
                        </EditItemTemplate>

                    <ItemTemplate>
                        <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                    </ItemTemplate>
                    <FooterTemplate>
                        <asp:TextBox ID="FooterName" runat="server"></asp:TextBox>
                            <asp:RequiredFieldValidator  ValidationGroup="Insert" ControlToValidate="FooterName" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Name Is A Required Field"></asp:RequiredFieldValidator>   
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="gender" SortExpression="gender">
                    <EditItemTemplate>
                        <asp:DropDownList ID="DropDownList1" runat="server" Text='<%# Bind("gender") %>'  > 
                            <asp:ListItem> Select Gender</asp:ListItem>
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>

                        </asp:DropDownList>
                        <asp:RequiredFieldValidator   ControlToValidate="DropDownList1" InitialValue="Select Gender" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Gender Is A Required Field"></asp:RequiredFieldValidator>   
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="Label3" runat="server" Text='<%# Bind("gender") %>'></asp:Label>
                    </ItemTemplate>

                    <FooterTemplate>
                        <asp:DropDownList ID="FooterDdlGender" runat="server">
                            <asp:ListItem> Select Gender</asp:ListItem>
                            <asp:ListItem>Male</asp:ListItem>
                            <asp:ListItem>Female</asp:ListItem>

                        </asp:DropDownList>
                         <asp:RequiredFieldValidator  ValidationGroup="Insert" ControlToValidate="FooterDdlGender" InitialValue="Select Gender" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Gender Is A Required Field"></asp:RequiredFieldValidator> 
                    </FooterTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="class" SortExpression="class">
                    <EditItemTemplate>
                        <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("class") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator ControlToValidate="TextBox3" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Class Is A Required Field"></asp:RequiredFieldValidator> 
                        </EditItemTemplate>

                    <ItemTemplate>
                        <asp:Label ID="Label4" runat="server" Text='<%# Bind("class") %>'></asp:Label>
                    </ItemTemplate>

                    <FooterTemplate>
                        <asp:TextBox ID="FooterClass" runat="server"></asp:TextBox>
                     <asp:RequiredFieldValidator  ValidationGroup="Insert" ControlToValidate="FooterClass" ForeColor="Red" Text="*" SetFocusOnError="true" runat="server" ErrorMessage="Name Is A Required Field"></asp:RequiredFieldValidator> 
                    </FooterTemplate>
                </asp:TemplateField>
            </Columns>
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:GridView>
        <asp:ValidationSummary  ValidationGroup="Insert" runat="server" BackColor="LightGray" Font-Size="Larger" ForeColor="Red"></asp:ValidationSummary>
         <asp:ValidationSummary   runat="server" BackColor="LightGray" Font-Size="Larger" ForeColor="Red"></asp:ValidationSummary>
        <div class="auto-style1">
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" DeleteCommand="DELETE FROM [Student] WHERE [Id] = @Id" InsertCommand="INSERT INTO [Student] ([name], [gender], [class]) VALUES (@name, @gender, @class)" ProviderName="<%$ ConnectionStrings:ConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Student]" UpdateCommand="UPDATE [Student] SET [name] = @name, [gender] = @gender, [class] = @class WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="class" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="name" Type="String" />
                    <asp:Parameter Name="gender" Type="String" />
                    <asp:Parameter Name="class" Type="Int32" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
        </div>
    </form>
</body>
</html>
